[package]
name = "nostratui"
version = "0.1.0"
edition = "2021"

[dependencies]
nostr-sdk = "0.40"
tokio = { version = ">=1.37", default-features = false }
clap = { version = "4.5.31", features = ["derive"] }
